version: '2'

volumes:
    db-data:
    vendor:
    var:

services:
    mysql:
        container_name: db
        image: mysql:5
        ports:
            - "33061:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: prestashop
            MYSQL_DATABASE: prestashop
        restart: always
    prestashop-git:
        container_name: presta
        build: .docker
        restart: always
        environment:
            PS_INSTALL_AUTO: 1
            DB_PASSWD: prestashop
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: localhost:8001
            PS_FOLDER_INSTALL: install-dev
            PS_FOLDER_ADMIN: admin-dev
            PS_LANGUAGE: es
            PS_COUNTRY: py
            ADMIN_MAIL: rauleburro@bellbird.com.py
            ADMIN_PASSWD: Bell2473.,

        command: [ "/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh" ]
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html/:delegated
            - vendor:/var/www/html/vendor
            - var:/var/www/html/var
